import{S as u,N as d,K as p,i as n,a as f}from"./assets/vendor-18157f21.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();new u(".swiper",{modules:[d,p],speed:400,spaceBetween:20,centeredSlides:!1,centeredSlidesBounds:!0,autoHeight:!0,slidesPerView:"auto",keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});const m="https://portfolio-js.b.goit.study/api/reviews",a=document.querySelector(".swiper-wrapper");async function g(){const r=await f.get(m,{});return console.log(r.data),r.data}function w(r){return r.map(o=>`
      <li class="swiper-slide">
      <p class="reviews-text">${o.review}</p>
      <div class="review-author-data">
          <a class="reviews-img-link" href="${o.avatar_url}">
          <img class="reviews-img" alt="author's avatar" src="${o.avatar_url}"/>
          </a>
          <p class="reviews-name">${o.author}</p>
      </div>
      </li>`).join("")}const c=document.querySelector(".error-container"),y=document.querySelector(".swiper");g().then(r=>{c.style.display="none",r.length>0?a.insertAdjacentHTML("beforeend",w(r)):(a.insertAdjacentHTML("beforeend","Not found"),n.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}))}).catch(r=>{y.style.display="none",c.insertAdjacentHTML("beforeend","<p>Not found</p>"),n.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}),console.log(r)});
//# sourceMappingURL=commonHelpers.js.map
