import{S as p,N as f,K as y,i as n,a as m}from"./assets/vendor-18157f21.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function u(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=u(e);fetch(e.href,r)}})();new p(".swiper",{modules:[f,y],speed:400,spaceBetween:20,centeredSlides:!1,centeredSlidesBounds:!0,autoHeight:!0,breakpoints:{1280:{slidesPerView:2},0:{slidesPerView:"auto"}},keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});const c=document.querySelector(".loader");function d(){c.style.visibility="collapsed"}function w(){c.style.visibility="visible"}d();const g="https://portfolio-js.b.goit.study/api/reviews",a=document.querySelector(".swiper-wrapper");async function h(){return(await m.get(g,{})).data}function v(o){return o.map(t=>`
      <li class="swiper-slide" id="review-slide">
      <p class="reviews-text">${t.review}</p>
      <div class="review-author-data">
          <a class="reviews-img-link" href="${t.avatar_url}">
          <img class="reviews-img" alt="author's avatar" src="${t.avatar_url}"/>
          </a>
          <p class="reviews-name">${t.author}</p>
      </div>
      </li>`).join("")}const l=document.querySelector(".error-container"),b=document.querySelector(".swiper");h().then(o=>{l.style.display="none",o.length>0?(w(),a.insertAdjacentHTML("beforeend",v(o))):(a.insertAdjacentHTML("beforeend","Not found"),n.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}))}).catch(o=>{b.style.display="none",l.insertAdjacentHTML("beforeend","<p>Not found</p>"),n.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"})}).finally(()=>{d()});
//# sourceMappingURL=commonHelpers.js.map
